### ISSUE TITLE
To-Do list for initial version

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Login-Flow-Android#1]
* [x] Configure `Glide` to use FluxC's network stack
* [x] Unify analytics tracking - currently using `AnalyticsTracker.track()` in the `LoginWpcomService` and `LoginListener.track()` everywhere else (since the service can't have a reference to `LoginListener`)
* [x] Use `dagger-android` to clean up fragment injection and drop the `inject()` methods from `LoginListener`
* [x] Move some pieces to the utils library
* [x] Extract unneeded methods (login prologue, for example) from `LoginListener`
* [x] Restore developer credential auto-fill
* [x] Allow dynamic setting of SDK/build tools/support library versions, to get around the library being used in apps with different support library versions
* [x] Add README with usage instructions
* [x] Set up checkstyle and Travis
* [x] A few resources should point to generic names instead of specifics (e.g. `loginButtonColor` instead of `wp_blue`), so that those can be clearly overwritten in the host app to change the styles
* [x] At least one new `LoginMode` is probably needed, supporting login only for WP.com or Jetpack sites (probably with some other customized messages/screens), which will be used by the WooCommerce app
* [x] Update README with detailed setup instructions once all the above is finalized
